name: take_my_tym
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  image_picker: ^1.0.7
  permission_handler:
  emoji_picker_flutter: ^2.1.1
  back_button_interceptor: ^5.0.2
  url_launcher: ^6.2.5
  path_provider: ^2.1.2
  http: ^1.2.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  vibration: ^1.8.4
  audioplayers: ^6.0.0 

  hive: ^2.2.3
  firebase_auth: ^4.17.8
  firebase_core: ^2.26.0
  cloud_firestore: ^4.15.10
  google_sign_in: ^6.2.1
  firebase_storage: ^11.7.0
  flutter_stripe: ^10.1.1
  
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.10+1
  animate_do: ^3.3.4
  iconly: ^1.0.1
  lottie: ^3.1.0
  animated_toggle_switch: ^0.8.2
  shimmer_pro: ^0.0.6
  button_animations: ^2.0.0+3
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/img/auth/
    - asset/img/
    - asset/json/
    - asset/img/test/
    - asset/img/icons/
    - asset/img/snackbar/
    - asset/img/ad/
    - assets/audio/

  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins/Poppins-Regular.ttf
        - asset: asset/font/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: asset/font/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: asset/font/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: asset/font/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: asset/font/Poppins/Poppins-Black.ttf
          weight: 900

    - family: Denton Condensed
      fonts:
        - asset: asset/font/Denton Condensed/DentonCondensedTest-Regular.otf
        - asset: asset/font/Denton Condensed/DentonCondensedTest-Black.otf
          weight: 800
        - asset: asset/font/Denton Condensed/DentonCondensedTest-Medium.otf
          weight: 900